<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassSeeder extends Seeder
{
    public function run(): void
    {
        $classes = [
            [
                'slug' => 'guerrier',
                'name' => 'Guerrier',
                'role' => 'Tank / DPS',
                'key_skill_name' => 'Charge Héroïque',
                'key_skill_description' => 'Fonce sans réfléchir',
                'mod_hp' => 30,
                'mod_atq' => 3,
                'mod_def' => 5,
                'mod_vit' => 0,
                'mod_cha' => -2,
                'mod_int' => -3,
                'primary_stats' => json_encode(['hp', 'atq', 'def']),
                'weapon_types' => json_encode(['epee', 'hache', 'masse']),
                'armor_types' => json_encode(['plaque', 'mailles']),
            ],
            [
                'slug' => 'mage',
                'name' => 'Mage',
                'role' => 'DPS Magique',
                'key_skill_name' => 'Boule de Feu',
                'key_skill_description' => 'Vise pas toujours bien',
                'mod_hp' => -20,
                'mod_atq' => -2,
                'mod_def' => -3,
                'mod_vit' => 2,
                'mod_cha' => 2,
                'mod_int' => 8,
                'primary_stats' => json_encode(['int', 'vit']),
                'weapon_types' => json_encode(['baguette', 'baton', 'orbe']),
                'armor_types' => json_encode(['tissu', 'robe']),
            ],
            [
                'slug' => 'voleur',
                'name' => 'Voleur',
                'role' => 'DPS / Utilitaire',
                'key_skill_name' => 'Coup en Traître',
                'key_skill_description' => 'Bonus si attaque par derrière',
                'mod_hp' => -10,
                'mod_atq' => 4,
                'mod_def' => -2,
                'mod_vit' => 6,
                'mod_cha' => 4,
                'mod_int' => 0,
                'primary_stats' => json_encode(['atq', 'vit', 'cha']),
                'weapon_types' => json_encode(['dague', 'epee_courte']),
                'armor_types' => json_encode(['cuir', 'tissu']),
            ],
            [
                'slug' => 'ranger',
                'name' => 'Ranger',
                'role' => 'DPS Distance',
                'key_skill_name' => 'Tir "Précis"',
                'key_skill_description' => 'Dépend du vent, de l\'humeur, de la lune',
                'mod_hp' => -5,
                'mod_atq' => 3,
                'mod_def' => -1,
                'mod_vit' => 4,
                'mod_cha' => 2,
                'mod_int' => 2,
                'primary_stats' => json_encode(['atq', 'vit']),
                'weapon_types' => json_encode(['arc', 'arbalete']),
                'armor_types' => json_encode(['cuir', 'mailles_legeres']),
            ],
            [
                'slug' => 'pretre',
                'name' => 'Prêtre',
                'role' => 'Soigneur',
                'key_skill_name' => 'Prière de Soin',
                'key_skill_description' => 'Résultats variables selon la foi du jour',
                'mod_hp' => 10,
                'mod_atq' => -3,
                'mod_def' => 2,
                'mod_vit' => -2,
                'mod_cha' => 5,
                'mod_int' => 5,
                'primary_stats' => json_encode(['int', 'cha', 'hp']),
                'weapon_types' => json_encode(['baton', 'masse_sainte']),
                'armor_types' => json_encode(['tissu', 'robe', 'mailles_legeres']),
            ],
            [
                'slug' => 'barde',
                'name' => 'Barde',
                'role' => 'Support / Buff',
                'key_skill_name' => 'Chanson Inspirante',
                'key_skill_description' => 'Ou pas, selon le public',
                'mod_hp' => -5,
                'mod_atq' => 0,
                'mod_def' => -1,
                'mod_vit' => 3,
                'mod_cha' => 8,
                'mod_int' => 3,
                'primary_stats' => json_encode(['cha', 'int']),
                'weapon_types' => json_encode(['instrument', 'dague', 'epee_courte']),
                'armor_types' => json_encode(['tissu', 'cuir']),
            ],
            [
                'slug' => 'barbare',
                'name' => 'Barbare',
                'role' => 'DPS Pur',
                'key_skill_name' => 'Rage',
                'key_skill_description' => 'Casse tout, y compris le décor',
                'mod_hp' => 20,
                'mod_atq' => 6,
                'mod_def' => -2,
                'mod_vit' => 2,
                'mod_cha' => -4,
                'mod_int' => -5,
                'primary_stats' => json_encode(['atq', 'hp']),
                'weapon_types' => json_encode(['hache_deux_mains', 'masse', 'n_importe_quoi']),
                'armor_types' => json_encode(['cuir', 'mailles']),
            ],
            [
                'slug' => 'necromancien',
                'name' => 'Nécromancien',
                'role' => 'Invocateur',
                'key_skill_name' => 'Invoquer Squelette',
                'key_skill_description' => 'Qui obéit... parfois',
                'mod_hp' => -15,
                'mod_atq' => 0,
                'mod_def' => 0,
                'mod_vit' => 0,
                'mod_cha' => -2,
                'mod_int' => 7,
                'primary_stats' => json_encode(['int']),
                'weapon_types' => json_encode(['baguette', 'baton', 'faux']),
                'armor_types' => json_encode(['tissu', 'robe']),
            ],
        ];

        foreach ($classes as $class) {
            DB::table('classes')->updateOrInsert(['slug' => $class['slug']], $class);
        }
    }
}
