<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConsumableSeeder extends Seeder
{
    public function run(): void
    {
        $consumables = [
            [
                'slug'        => 'potion_soin_petit',
                'name'        => 'Petite Potion de Soin',
                'description' => 'Restaure 50 HP à toute l\'équipe.',
                'flavor_text' => '"Goût framboise. Ou peut-être de chaussette. Difficile à dire." — Gérard',
                'effect_type' => 'heal_hp',
                'effect_value' => 50,
                'duration_turns' => 0,
                'rarity'      => 'commun',
                'buy_price'   => 15,
                'sell_value'  => 5,
                'stack_max'   => 99,
            ],
            [
                'slug'        => 'potion_soin_grand',
                'name'        => 'Grande Potion de Soin',
                'description' => 'Restaure 200 HP à toute l\'équipe.',
                'flavor_text' => '"Cette fois c\'est du sérieux. Enfin, autant qu\'on peut l\'être." — Gérard',
                'effect_type' => 'heal_hp',
                'effect_value' => 200,
                'duration_turns' => 0,
                'rarity'      => 'peu_commun',
                'buy_price'   => 50,
                'sell_value'  => 20,
                'stack_max'   => 99,
            ],
            [
                'slug'        => 'elixir_vigueur',
                'name'        => 'Élixir de Vigueur',
                'description' => 'Restaure 50% des HP maximum de toute l\'équipe.',
                'flavor_text' => '"Ça pue mais ça marche. Plus ou moins." — Gérard',
                'effect_type' => 'restore_hp_pct',
                'effect_value' => 50,
                'duration_turns' => 0,
                'rarity'      => 'rare',
                'buy_price'   => 120,
                'sell_value'  => 50,
                'stack_max'   => 20,
            ],
            [
                'slug'        => 'parchemin_experience',
                'name'        => 'Parchemin d\'Expérience',
                'description' => 'Accorde 100 XP à tous les héros.',
                'flavor_text' => '"Lu et approuvé par quelqu\'un qui savait lire." — sceau illisible',
                'effect_type' => 'xp_boost',
                'effect_value' => 100,
                'duration_turns' => 0,
                'rarity'      => 'peu_commun',
                'buy_price'   => 80,
                'sell_value'  => 30,
                'stack_max'   => 10,
            ],
            [
                'slug'        => 'potion_or',
                'name'        => 'Potion d\'Avarice',
                'description' => 'Accorde 50 pièces d\'or. Oui, c\'est une potion.',
                'flavor_text' => '"Ne demandez pas comment ça fonctionne." — Gérard',
                'effect_type' => 'gold_boost',
                'effect_value' => 50,
                'duration_turns' => 0,
                'rarity'      => 'commun',
                'buy_price'   => 30,
                'sell_value'  => 10,
                'stack_max'   => 99,
            ],
            [
                'slug'           => 'antidote_incompetence',
                'name'           => 'Antidote d\'Incompétence',
                'description'    => 'Supprime tous les debuffs actifs de l\'équipe.',
                'flavor_text'    => '"Efficace contre les malédictions, les empoisonnements, et les lundis matin." — étiquette',
                'effect_type'    => 'cure_debuff',
                'effect_value'   => 0,
                'duration_turns' => 0,
                'rarity'         => 'rare',
                'buy_price'      => 200,
                'sell_value'     => 80,
                'stack_max'      => 5,
            ],

            // ── Consommables de la Taverne (prix = buy_price × niveau_zone) ──
            // Le buy_price stocké est le multiplicateur par niveau de zone (§5.2).
            [
                'slug'           => 'taverne_potion_mineure',
                'name'           => 'Potion de Soin Mineure',
                'description'    => 'Soigne 20% des PV max de toute l\'équipe.',
                'flavor_text'    => '"Basique. Honnête. Comme la tenancière." — ardoise de taverne',
                'effect_type'    => 'restore_hp_pct',
                'effect_value'   => 20,
                'duration_turns' => 0,
                'rarity'         => 'commun',
                'buy_price'      => 30,
                'sell_value'     => 10,
                'stack_max'      => 99,
            ],
            [
                'slug'           => 'taverne_potion_soin',
                'name'           => 'Potion de Soin',
                'description'    => 'Soigne 40% des PV max de toute l\'équipe.',
                'flavor_text'    => '"Le bestseller de la maison. Après la bière." — ardoise de taverne',
                'effect_type'    => 'restore_hp_pct',
                'effect_value'   => 40,
                'duration_turns' => 0,
                'rarity'         => 'commun',
                'buy_price'      => 80,
                'sell_value'     => 25,
                'stack_max'      => 99,
            ],
            [
                'slug'           => 'taverne_potion_majeure',
                'name'           => 'Potion de Soin Majeure',
                'description'    => 'Soigne 70% des PV max de toute l\'équipe.',
                'flavor_text'    => '"Pour les situations désespérées. Ne demandez pas les ingrédients." — ardoise de taverne',
                'effect_type'    => 'restore_hp_pct',
                'effect_value'   => 70,
                'duration_turns' => 0,
                'rarity'         => 'peu_commun',
                'buy_price'      => 200,
                'sell_value'     => 70,
                'stack_max'      => 20,
            ],
            [
                'slug'           => 'taverne_parchemin_fuite',
                'name'           => 'Parchemin de Fuite',
                'description'    => 'Garantit une fuite réussie. La tenancière ne vous jugera qu\'un peu.',
                'flavor_text'    => '"La discrétion est un service supplémentaire. Payant." — ardoise de taverne',
                'effect_type'    => 'guaranteed_flee',
                'effect_value'   => 1,
                'duration_turns' => 0,
                'rarity'         => 'commun',
                'buy_price'      => 50,
                'sell_value'     => 15,
                'stack_max'      => 10,
            ],
            [
                'slug'           => 'taverne_pierre_aiguisage',
                'name'           => 'Pierre d\'Aiguisage',
                'description'    => '+10% ATQ pour 5 combats.',
                'flavor_text'    => '"Le forgeron du coin l\'utilise. Enfin, il dit que c\'est lui." — ardoise de taverne',
                'effect_type'    => 'buff_atq_pct',
                'effect_value'   => 10,
                'duration_turns' => 5,
                'rarity'         => 'commun',
                'buy_price'      => 100,
                'sell_value'     => 35,
                'stack_max'      => 20,
            ],
            [
                'slug'           => 'taverne_encens_protection',
                'name'           => 'Encens de Protection',
                'description'    => '+10% DEF pour 5 combats. Ça sent le bois de santal et la survie.',
                'flavor_text'    => '"On brûle, et l\'armure tient mieux. Logique de taverne." — ardoise de taverne',
                'effect_type'    => 'buff_def_pct',
                'effect_value'   => 10,
                'duration_turns' => 5,
                'rarity'         => 'commun',
                'buy_price'      => 100,
                'sell_value'     => 35,
                'stack_max'      => 20,
            ],
            [
                'slug'           => 'taverne_elixir_vitesse',
                'name'           => 'Élixir de Vitesse',
                'description'    => '+15% VIT pour 5 combats. Attention : les héros Gourmands l\'avalent sans prévenir.',
                'flavor_text'    => '"Ça picote. C\'est bon signe, paraît-il." — ardoise de taverne',
                'effect_type'    => 'buff_vit_pct',
                'effect_value'   => 15,
                'duration_turns' => 5,
                'rarity'         => 'peu_commun',
                'buy_price'      => 120,
                'sell_value'     => 40,
                'stack_max'      => 20,
            ],
            [
                'slug'           => 'taverne_antidote',
                'name'           => 'Antidote',
                'description'    => 'Retire le statut Empoisonné de toute l\'équipe.',
                'flavor_text'    => '"Goût de réglisse. Ou de détresse. Surtout de détresse." — ardoise de taverne',
                'effect_type'    => 'cure_poison',
                'effect_value'   => 1,
                'duration_turns' => 0,
                'rarity'         => 'commun',
                'buy_price'      => 60,
                'sell_value'     => 20,
                'stack_max'      => 99,
            ],
            [
                'slug'           => 'taverne_kit_reparation_basique',
                'name'           => 'Kit de Réparation Basique',
                'description'    => 'Répare 20 points de durabilité sur un objet.',
                'flavor_text'    => '"On fait ce qu\'on peut avec ce qu\'on a." — ardoise de taverne',
                'effect_type'    => 'repair_durability',
                'effect_value'   => 20,
                'duration_turns' => 0,
                'rarity'         => 'commun',
                'buy_price'      => 150,
                'sell_value'     => 50,
                'stack_max'      => 10,
            ],
            [
                'slug'           => 'taverne_kit_reparation_avance',
                'name'           => 'Kit de Réparation Avancé',
                'description'    => 'Répare 50 points de durabilité sur un objet.',
                'flavor_text'    => '"Comprend une notice. En nain. Bonne chance." — ardoise de taverne',
                'effect_type'    => 'repair_durability',
                'effect_value'   => 50,
                'duration_turns' => 0,
                'rarity'         => 'peu_commun',
                'buy_price'      => 400,
                'sell_value'     => 140,
                'stack_max'      => 5,
            ],
            [
                'slug'           => 'taverne_torche_eternelle',
                'name'           => 'Torche Éternelle',
                'description'    => 'Évite le debuff "Explorer sans torche" dans les donjons obscurs.',
                'flavor_text'    => '"Ne s\'éteint jamais. Même sous l\'eau. Ne demandez pas pourquoi." — ardoise de taverne',
                'effect_type'    => 'dungeon_torch',
                'effect_value'   => 1,
                'duration_turns' => 0,
                'rarity'         => 'peu_commun',
                'buy_price'      => 200,
                'sell_value'     => 70,
                'stack_max'      => 5,
            ],
        ];

        foreach ($consumables as $c) {
            DB::table('consumables')->updateOrInsert(['slug' => $c['slug']], $c);
        }
    }
}
