<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonsterSeeder extends Seeder
{
    public function run(): void
    {
        $prairieId = DB::table('zones')->where('slug', 'prairie')->value('id');
        $foretId   = DB::table('zones')->where('slug', 'foret_elfes')->value('id');
        $minesId   = DB::table('zones')->where('slug', 'mines_nain')->value('id');
        $maraisId  = DB::table('zones')->where('slug', 'marais_bureaucratie')->value('id');
        $tourId    = DB::table('zones')->where('slug', 'tour_mage_distrait')->value('id');
        $cimetId   = DB::table('zones')->where('slug', 'cimetiere_syndique')->value('id');
        $volcanId  = DB::table('zones')->where('slug', 'volcan_dragon_retraite')->value('id');
        $capitId   = DB::table('zones')->where('slug', 'capitale_incompetents')->value('id');

        $monsters = [
            // ── Zone 1 : Prairie ──
            ['zone_id' => $prairieId, 'name' => 'Rat Peureux', 'slug' => 'rat_peureux', 'monster_type' => 'normal', 'level' => 1, 'base_hp' => 15, 'base_atq' => 3, 'base_def' => 1, 'base_vit' => 8, 'base_int' => 0, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 12, 'gold_min' => 0, 'gold_max' => 2, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random']), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Slime Vert', 'slug' => 'slime_vert', 'monster_type' => 'normal', 'level' => 1, 'base_hp' => 25, 'base_atq' => 2, 'base_def' => 3, 'base_vit' => 2, 'base_int' => 0, 'base_cha' => 0, 'element' => 'poison', 'xp_reward' => 10, 'gold_min' => 1, 'gold_max' => 3, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'lowest_hp']), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Gobelin Chapardeur', 'slug' => 'gobelin_chapardeur', 'monster_type' => 'normal', 'level' => 2, 'base_hp' => 20, 'base_atq' => 5, 'base_def' => 2, 'base_vit' => 10, 'base_int' => 0, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 18, 'gold_min' => 3, 'gold_max' => 8, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'lowest_hp', 'steals_gold' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Loup Solitaire', 'slug' => 'loup_solitaire', 'monster_type' => 'normal', 'level' => 2, 'base_hp' => 30, 'base_atq' => 7, 'base_def' => 2, 'base_vit' => 12, 'base_int' => 0, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 22, 'gold_min' => 0, 'gold_max' => 5, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random']), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Épouvantail Animé', 'slug' => 'epouvantail_anime', 'monster_type' => 'normal', 'level' => 3, 'base_hp' => 35, 'base_atq' => 6, 'base_def' => 4, 'base_vit' => 4, 'base_int' => 2, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 28, 'gold_min' => 2, 'gold_max' => 6, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'fear_chance' => 15]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Abeille Géante', 'slug' => 'abeille_geante', 'monster_type' => 'normal', 'level' => 3, 'base_hp' => 20, 'base_atq' => 8, 'base_def' => 1, 'base_vit' => 15, 'base_int' => 0, 'base_cha' => 0, 'element' => 'poison', 'xp_reward' => 25, 'gold_min' => 0, 'gold_max' => 3, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'poison_chance' => 25]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Le Fermier Possédé', 'slug' => 'fermier_possede', 'monster_type' => 'mini_boss', 'level' => 4, 'base_hp' => 150, 'base_atq' => 20, 'base_def' => 12, 'base_vit' => 8, 'base_int' => 5, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 120, 'gold_min' => 20, 'gold_max' => 40, 'loot_bonus' => 25, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'enrage_at_50_percent' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $prairieId, 'name' => 'Le Taureau du Pré Maudit', 'slug' => 'taureau_pre_maudit', 'monster_type' => 'boss', 'level' => 5, 'base_hp' => 400, 'base_atq' => 25, 'base_def' => 15, 'base_vit' => 10, 'base_int' => 3, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 300, 'gold_min' => 50, 'gold_max' => 100, 'loot_bonus' => 50, 'behavior_data' => json_encode(['priority' => 'random', 'charge_every_3_turns' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 130, 'narrator_text' => 'Le taureau est en colère. Plus qu\'avant. C\'est possible.']), 'is_active' => 1],

            // ── Zone 2 : Forêt des Elfes Vexés ──
            ['zone_id' => $foretId, 'name' => 'Elfe Archer Contrarié', 'slug' => 'elfe_archer_contrarie', 'monster_type' => 'normal', 'level' => 5, 'base_hp' => 40, 'base_atq' => 12, 'base_def' => 4, 'base_vit' => 14, 'base_int' => 6, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 40, 'gold_min' => 5, 'gold_max' => 12, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'lowest_hp', 'snipe_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'Fée Malveillante', 'slug' => 'fee_malveillante', 'monster_type' => 'normal', 'level' => 6, 'base_hp' => 35, 'base_atq' => 10, 'base_def' => 3, 'base_vit' => 18, 'base_int' => 12, 'base_cha' => 0, 'element' => 'sacre', 'xp_reward' => 45, 'gold_min' => 3, 'gold_max' => 10, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'hex_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'Loup des Bois Enchanté', 'slug' => 'loup_bois_enchante', 'monster_type' => 'normal', 'level' => 7, 'base_hp' => 65, 'base_atq' => 15, 'base_def' => 6, 'base_vit' => 16, 'base_int' => 4, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 55, 'gold_min' => 4, 'gold_max' => 10, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random']), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'Plante Carnivore Pédante', 'slug' => 'plante_carnivore_pedante', 'monster_type' => 'normal', 'level' => 8, 'base_hp' => 80, 'base_atq' => 14, 'base_def' => 10, 'base_vit' => 3, 'base_int' => 8, 'base_cha' => 0, 'element' => 'poison', 'xp_reward' => 60, 'gold_min' => 2, 'gold_max' => 8, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'root_chance' => 25]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'Dryade Contrariée', 'slug' => 'dryade_contrariee', 'monster_type' => 'normal', 'level' => 9, 'base_hp' => 70, 'base_atq' => 16, 'base_def' => 8, 'base_vit' => 10, 'base_int' => 14, 'base_cha' => 5, 'element' => 'sacre', 'xp_reward' => 68, 'gold_min' => 6, 'gold_max' => 14, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'heal_self_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'Araignée de Soie Magique', 'slug' => 'araignee_soie_magique', 'monster_type' => 'normal', 'level' => 10, 'base_hp' => 55, 'base_atq' => 20, 'base_def' => 5, 'base_vit' => 20, 'base_int' => 6, 'base_cha' => 0, 'element' => 'poison', 'xp_reward' => 72, 'gold_min' => 5, 'gold_max' => 12, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'web_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'Elara l\'Elfe Vexée (mini-boss)', 'slug' => 'elara_elfe_vexee_mini', 'monster_type' => 'mini_boss', 'level' => 10, 'base_hp' => 280, 'base_atq' => 35, 'base_def' => 20, 'base_vit' => 22, 'base_int' => 28, 'base_cha' => 10, 'element' => 'sacre', 'xp_reward' => 350, 'gold_min' => 40, 'gold_max' => 80, 'loot_bonus' => 30, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'enrage_at_50_percent' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $foretId, 'name' => 'L\'Esprit de la Forêt (Très Énervé)', 'slug' => 'esprit_foret_tres_enerve', 'monster_type' => 'boss', 'level' => 12, 'base_hp' => 900, 'base_atq' => 45, 'base_def' => 30, 'base_vit' => 18, 'base_int' => 40, 'base_cha' => 0, 'element' => 'sacre', 'xp_reward' => 750, 'gold_min' => 100, 'gold_max' => 200, 'loot_bonus' => 60, 'behavior_data' => json_encode(['priority' => 'random', 'summon_every_4_turns' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 140, 'narrator_text' => 'L\'Esprit est en colère. Un arbre vous a regardé méchamment.']), 'is_active' => 1],

            // ── Zone 3 : Mines du Nain Ivre ──
            ['zone_id' => $minesId, 'name' => 'Rat de Mine Alcoolisé', 'slug' => 'rat_mine_alcoolise', 'monster_type' => 'normal', 'level' => 12, 'base_hp' => 90, 'base_atq' => 22, 'base_def' => 8, 'base_vit' => 10, 'base_int' => 0, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 90, 'gold_min' => 8, 'gold_max' => 18, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'confused_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Golem de Pierre Ébréché', 'slug' => 'golem_pierre_ebreche', 'monster_type' => 'normal', 'level' => 13, 'base_hp' => 160, 'base_atq' => 28, 'base_def' => 25, 'base_vit' => 4, 'base_int' => 0, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 100, 'gold_min' => 5, 'gold_max' => 15, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random']), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Kobold Mineur Syndiqué', 'slug' => 'kobold_mineur_syndique', 'monster_type' => 'normal', 'level' => 14, 'base_hp' => 110, 'base_atq' => 26, 'base_def' => 14, 'base_vit' => 16, 'base_int' => 8, 'base_cha' => 5, 'element' => 'physique', 'xp_reward' => 110, 'gold_min' => 12, 'gold_max' => 25, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'lowest_hp', 'call_reinforcements' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Chauve-Souris Géante Minérale', 'slug' => 'chauve_souris_minerale', 'monster_type' => 'normal', 'level' => 15, 'base_hp' => 100, 'base_atq' => 30, 'base_def' => 10, 'base_vit' => 25, 'base_int' => 5, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 115, 'gold_min' => 6, 'gold_max' => 16, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'blind_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Troll des Tunnels', 'slug' => 'troll_tunnels', 'monster_type' => 'normal', 'level' => 17, 'base_hp' => 200, 'base_atq' => 35, 'base_def' => 20, 'base_vit' => 6, 'base_int' => 2, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 140, 'gold_min' => 15, 'gold_max' => 30, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'regenerate_per_turn' => 5]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Cristal Gardien', 'slug' => 'cristal_gardien', 'monster_type' => 'normal', 'level' => 18, 'base_hp' => 140, 'base_atq' => 32, 'base_def' => 30, 'base_vit' => 8, 'base_int' => 20, 'base_cha' => 0, 'element' => 'sacre', 'xp_reward' => 130, 'gold_min' => 10, 'gold_max' => 25, 'loot_bonus' => 20, 'behavior_data' => json_encode(['priority' => 'random', 'reflect_magic_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Thorin Ivre-Furieux (mini-boss)', 'slug' => 'thorin_ivre_furieux_mini', 'monster_type' => 'mini_boss', 'level' => 18, 'base_hp' => 550, 'base_atq' => 55, 'base_def' => 35, 'base_vit' => 12, 'base_int' => 8, 'base_cha' => 15, 'element' => 'physique', 'xp_reward' => 650, 'gold_min' => 80, 'gold_max' => 150, 'loot_bonus' => 35, 'behavior_data' => json_encode(['priority' => 'random', 'enrage_at_50_percent' => true, 'beer_throw_chance' => 25]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $minesId, 'name' => 'Le Dragon des Mines (Retraité)', 'slug' => 'dragon_mines_retraite', 'monster_type' => 'boss', 'level' => 20, 'base_hp' => 1800, 'base_atq' => 70, 'base_def' => 50, 'base_vit' => 15, 'base_int' => 35, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 1500, 'gold_min' => 200, 'gold_max' => 400, 'loot_bonus' => 70, 'behavior_data' => json_encode(['priority' => 'random', 'breath_every_5_turns' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 125, 'narrator_text' => 'Le dragon est sorti de sa retraite. Techniquement, vous êtes en train de déranger un retraité. Le Narrateur est gêné pour vous.']), 'is_active' => 1],

            // ── Zone 4 : Marais de la Bureaucratie ──
            ['zone_id' => $maraisId, 'name' => 'Squelette Administratif', 'slug' => 'squelette_administratif', 'monster_type' => 'normal', 'level' => 20, 'base_hp' => 150, 'base_atq' => 40, 'base_def' => 22, 'base_vit' => 12, 'base_int' => 15, 'base_cha' => 5, 'element' => 'ombre', 'xp_reward' => 160, 'gold_min' => 15, 'gold_max' => 30, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'form_request_chance' => 35]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Fantôme Bureaucrate', 'slug' => 'fantome_bureaucrate', 'monster_type' => 'normal', 'level' => 22, 'base_hp' => 130, 'base_atq' => 38, 'base_def' => 15, 'base_vit' => 18, 'base_int' => 30, 'base_cha' => 10, 'element' => 'ombre', 'xp_reward' => 175, 'gold_min' => 10, 'gold_max' => 25, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'dodge_chance_bonus' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Vase Marécageux Conscient', 'slug' => 'vase_marecageux_conscient', 'monster_type' => 'normal', 'level' => 23, 'base_hp' => 220, 'base_atq' => 35, 'base_def' => 35, 'base_vit' => 3, 'base_int' => 5, 'base_cha' => 0, 'element' => 'poison', 'xp_reward' => 170, 'gold_min' => 5, 'gold_max' => 15, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'slow_chance' => 40]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Inspecteur des Finances Mort-Vivant', 'slug' => 'inspecteur_finances_mort_vivant', 'monster_type' => 'normal', 'level' => 25, 'base_hp' => 180, 'base_atq' => 45, 'base_def' => 28, 'base_vit' => 14, 'base_int' => 35, 'base_cha' => 20, 'element' => 'ombre', 'xp_reward' => 200, 'gold_min' => 20, 'gold_max' => 45, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'gold_steal_chance' => 25]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Hydre des Formulaires', 'slug' => 'hydre_formulaires', 'monster_type' => 'normal', 'level' => 26, 'base_hp' => 280, 'base_atq' => 42, 'base_def' => 25, 'base_vit' => 10, 'base_int' => 20, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 215, 'gold_min' => 18, 'gold_max' => 35, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'multi_attack' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Liche-Comptable', 'slug' => 'liche_comptable', 'monster_type' => 'normal', 'level' => 28, 'base_hp' => 200, 'base_atq' => 50, 'base_def' => 20, 'base_vit' => 12, 'base_int' => 55, 'base_cha' => 15, 'element' => 'sacre', 'xp_reward' => 240, 'gold_min' => 25, 'gold_max' => 55, 'loot_bonus' => 20, 'behavior_data' => json_encode(['priority' => 'lowest_hp', 'curse_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Le Directeur des Impôts (mini-boss)', 'slug' => 'directeur_impots_mini', 'monster_type' => 'mini_boss', 'level' => 28, 'base_hp' => 900, 'base_atq' => 75, 'base_def' => 50, 'base_vit' => 16, 'base_int' => 60, 'base_cha' => 30, 'element' => 'ombre', 'xp_reward' => 1200, 'gold_min' => 150, 'gold_max' => 280, 'loot_bonus' => 40, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'enrage_at_50_percent' => true, 'tax_steal_chance' => 35]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $maraisId, 'name' => 'Le Kraken Comptable', 'slug' => 'kraken_comptable', 'monster_type' => 'boss', 'level' => 30, 'base_hp' => 4000, 'base_atq' => 90, 'base_def' => 60, 'base_vit' => 14, 'base_int' => 80, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 3000, 'gold_min' => 400, 'gold_max' => 800, 'loot_bonus' => 80, 'behavior_data' => json_encode(['priority' => 'random', 'audit_every_5_turns' => true, 'tentacle_attack' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 130, 'narrator_text' => 'Le Kraken sort ses calculatrices. Huit tentacules. Huit calculatrices. Votre déclaration d\'impôts est en retard.']), 'is_active' => 1],

            // ── Zone 5 : La Tour du Mage Distrait ──
            ['zone_id' => $tourId, 'name' => 'Balai Enchanté', 'slug' => 'balai_enchante', 'monster_type' => 'normal', 'level' => 30, 'base_hp' => 180, 'base_atq' => 55, 'base_def' => 15, 'base_vit' => 28, 'base_int' => 10, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 280, 'gold_min' => 25, 'gold_max' => 55, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random', 'dodge_bonus' => 15]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Livre Mordeur', 'slug' => 'livre_mordeur', 'monster_type' => 'normal', 'level' => 32, 'base_hp' => 160, 'base_atq' => 70, 'base_def' => 18, 'base_vit' => 16, 'base_int' => 20, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 310, 'gold_min' => 20, 'gold_max' => 45, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'ambush_first_turn' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Élémentaire Instable', 'slug' => 'elementaire_instable', 'monster_type' => 'normal', 'level' => 34, 'base_hp' => 220, 'base_atq' => 62, 'base_def' => 20, 'base_vit' => 18, 'base_int' => 30, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 330, 'gold_min' => 30, 'gold_max' => 60, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'explode_at_20_percent' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Armure Animée', 'slug' => 'armure_animee', 'monster_type' => 'normal', 'level' => 35, 'base_hp' => 320, 'base_atq' => 52, 'base_def' => 60, 'base_vit' => 5, 'base_int' => 5, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 340, 'gold_min' => 20, 'gold_max' => 45, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'reflect_chance' => 25]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Apprenti Raté', 'slug' => 'apprenti_rate', 'monster_type' => 'normal', 'level' => 36, 'base_hp' => 140, 'base_atq' => 58, 'base_def' => 12, 'base_vit' => 20, 'base_int' => 40, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 350, 'gold_min' => 25, 'gold_max' => 55, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random', 'random_element_chance' => 40]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Gargouille', 'slug' => 'gargouille', 'monster_type' => 'normal', 'level' => 38, 'base_hp' => 260, 'base_atq' => 65, 'base_def' => 40, 'base_vit' => 10, 'base_int' => 15, 'base_cha' => 0, 'element' => 'glace', 'xp_reward' => 380, 'gold_min' => 30, 'gold_max' => 65, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'charge_first_turn' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Horloge Folle', 'slug' => 'horloge_folle', 'monster_type' => 'normal', 'level' => 39, 'base_hp' => 200, 'base_atq' => 48, 'base_def' => 22, 'base_vit' => 35, 'base_int' => 25, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 370, 'gold_min' => 25, 'gold_max' => 55, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random', 'initiative_manipulation' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Le Familiar Rebelle', 'slug' => 'familiar_rebelle', 'monster_type' => 'mini_boss', 'level' => 37, 'base_hp' => 1800, 'base_atq' => 95, 'base_def' => 35, 'base_vit' => 30, 'base_int' => 70, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 2200, 'gold_min' => 300, 'gold_max' => 550, 'loot_bonus' => 45, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'buff_inversion_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $tourId, 'name' => 'Le Mage Distrait', 'slug' => 'mage_distrait', 'monster_type' => 'boss', 'level' => 42, 'base_hp' => 6000, 'base_atq' => 110, 'base_def' => 45, 'base_vit' => 20, 'base_int' => 120, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 5500, 'gold_min' => 700, 'gold_max' => 1400, 'loot_bonus' => 90, 'behavior_data' => json_encode(['priority' => 'random', 'change_element_every_3_turns' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 120, 'narrator_text' => 'Le Mage a perdu le contrôle. C\'est à la fois terrifiant et hilarant.']), 'is_active' => 1],

            // ── Zone 6 : Le Cimetière Syndiqué ──
            ['zone_id' => $cimetId, 'name' => 'Squelette Syndiqué', 'slug' => 'squelette_syndique', 'monster_type' => 'normal', 'level' => 42, 'base_hp' => 230, 'base_atq' => 65, 'base_def' => 35, 'base_vit' => 12, 'base_int' => 15, 'base_cha' => 5, 'element' => 'ombre', 'xp_reward' => 400, 'gold_min' => 35, 'gold_max' => 70, 'loot_bonus' => 0, 'behavior_data' => json_encode(['priority' => 'random', 'strike_pause_turns' => [4, 8]]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Zombie Fonctionnaire', 'slug' => 'zombie_fonctionnaire', 'monster_type' => 'normal', 'level' => 44, 'base_hp' => 310, 'base_atq' => 55, 'base_def' => 45, 'base_vit' => 5, 'base_int' => 25, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 420, 'gold_min' => 25, 'gold_max' => 55, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'drain_and_regen' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Fantôme Plaintif', 'slug' => 'fantome_plaintif', 'monster_type' => 'normal', 'level' => 46, 'base_hp' => 190, 'base_atq' => 78, 'base_def' => 12, 'base_vit' => 24, 'base_int' => 30, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 440, 'gold_min' => 30, 'gold_max' => 60, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'armor_pierce_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Goule Affamée', 'slug' => 'goule_affamee', 'monster_type' => 'normal', 'level' => 47, 'base_hp' => 260, 'base_atq' => 88, 'base_def' => 18, 'base_vit' => 20, 'base_int' => 10, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 460, 'gold_min' => 30, 'gold_max' => 65, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'lowest_hp']), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Vampire Comptable', 'slug' => 'vampire_comptable', 'monster_type' => 'normal', 'level' => 49, 'base_hp' => 220, 'base_atq' => 72, 'base_def' => 25, 'base_vit' => 22, 'base_int' => 35, 'base_cha' => 10, 'element' => 'ombre', 'xp_reward' => 490, 'gold_min' => 40, 'gold_max' => 80, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'double_drain' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Revenant en Armure', 'slug' => 'revenant_armure', 'monster_type' => 'normal', 'level' => 51, 'base_hp' => 400, 'base_atq' => 58, 'base_def' => 65, 'base_vit' => 7, 'base_int' => 15, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 510, 'gold_min' => 35, 'gold_max' => 70, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'reflect_magic_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Le Délégué Syndical des Morts', 'slug' => 'delegue_syndical_morts', 'monster_type' => 'mini_boss', 'level' => 50, 'base_hp' => 2800, 'base_atq' => 95, 'base_def' => 55, 'base_vit' => 14, 'base_int' => 60, 'base_cha' => 20, 'element' => 'ombre', 'xp_reward' => 3500, 'gold_min' => 500, 'gold_max' => 900, 'loot_bonus' => 50, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'general_strike_every_5_turns' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $cimetId, 'name' => 'Le Nécromancien Retraité', 'slug' => 'necromancien_retraite', 'monster_type' => 'boss', 'level' => 55, 'base_hp' => 8000, 'base_atq' => 105, 'base_def' => 50, 'base_vit' => 18, 'base_int' => 130, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 8000, 'gold_min' => 1000, 'gold_max' => 2000, 'loot_bonus' => 95, 'behavior_data' => json_encode(['priority' => 'random', 'summon_revenants_every_6_turns' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 125, 'narrator_text' => 'Il a décidé de faire le travail lui-même. La retraite est finie.']), 'is_active' => 1],

            // ── Zone 7 : Le Volcan du Dragon Retraité ──
            ['zone_id' => $volcanId, 'name' => 'Élémentaire de Feu', 'slug' => 'elementaire_feu_volcan', 'monster_type' => 'normal', 'level' => 55, 'base_hp' => 300, 'base_atq' => 90, 'base_def' => 25, 'base_vit' => 20, 'base_int' => 30, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 550, 'gold_min' => 45, 'gold_max' => 90, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'explode_on_death' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Diablotin Farceur', 'slug' => 'diablotin_farceur', 'monster_type' => 'normal', 'level' => 57, 'base_hp' => 170, 'base_atq' => 75, 'base_def' => 12, 'base_vit' => 35, 'base_int' => 20, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 560, 'gold_min' => 40, 'gold_max' => 80, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random', 'hit_and_run' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Tortue de Lave', 'slug' => 'tortue_lave', 'monster_type' => 'normal', 'level' => 59, 'base_hp' => 500, 'base_atq' => 52, 'base_def' => 80, 'base_vit' => 3, 'base_int' => 10, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 580, 'gold_min' => 40, 'gold_max' => 80, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'reflect_and_regen' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Phénix Mineur', 'slug' => 'phenix_mineur', 'monster_type' => 'normal', 'level' => 61, 'base_hp' => 240, 'base_atq' => 85, 'base_def' => 18, 'base_vit' => 25, 'base_int' => 25, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 610, 'gold_min' => 50, 'gold_max' => 100, 'loot_bonus' => 20, 'behavior_data' => json_encode(['priority' => 'random', 'revive_once_at_50_percent' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Forgeron Damné', 'slug' => 'forgeron_damne', 'monster_type' => 'normal', 'level' => 63, 'base_hp' => 360, 'base_atq' => 98, 'base_def' => 40, 'base_vit' => 12, 'base_int' => 20, 'base_cha' => 5, 'element' => 'feu', 'xp_reward' => 635, 'gold_min' => 55, 'gold_max' => 110, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'buff_allies_then_strike' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Wyrm de Lave', 'slug' => 'wyrm_lave', 'monster_type' => 'normal', 'level' => 65, 'base_hp' => 420, 'base_atq' => 80, 'base_def' => 35, 'base_vit' => 15, 'base_int' => 15, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 660, 'gold_min' => 55, 'gold_max' => 110, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'multi_attack' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Le Gardien du Volcan', 'slug' => 'gardien_volcan', 'monster_type' => 'mini_boss', 'level' => 65, 'base_hp' => 4000, 'base_atq' => 125, 'base_def' => 70, 'base_vit' => 10, 'base_int' => 40, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 5000, 'gold_min' => 700, 'gold_max' => 1300, 'loot_bonus' => 55, 'behavior_data' => json_encode(['priority' => 'random', 'eruption_every_4_turns' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $volcanId, 'name' => 'Le Dragon Retraité', 'slug' => 'dragon_retraite', 'monster_type' => 'boss', 'level' => 70, 'base_hp' => 12000, 'base_atq' => 140, 'base_def' => 85, 'base_vit' => 15, 'base_int' => 60, 'base_cha' => 0, 'element' => 'feu', 'xp_reward' => 12000, 'gold_min' => 1500, 'gold_max' => 3000, 'loot_bonus' => 100, 'behavior_data' => json_encode(['priority' => 'random', 'passive_first_3_turns' => true, 'skip_1_in_4_turns' => true]), 'phase2_data' => json_encode(['hp_threshold' => 50, 'stat_multiplier' => 120, 'narrator_text' => 'Vous avez renversé son thé. Vous allez payer.']), 'is_active' => 1],

            // ── Zone 8 : La Capitale des Incompétents ──
            ['zone_id' => $capitId, 'name' => 'Garde Corrompu', 'slug' => 'garde_corrompu', 'monster_type' => 'normal', 'level' => 70, 'base_hp' => 430, 'base_atq' => 105, 'base_def' => 60, 'base_vit' => 15, 'base_int' => 20, 'base_cha' => 15, 'element' => 'physique', 'xp_reward' => 700, 'gold_min' => 60, 'gold_max' => 120, 'loot_bonus' => 5, 'behavior_data' => json_encode(['priority' => 'random', 'taunt_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Voleur de Grand Chemin', 'slug' => 'voleur_grand_chemin', 'monster_type' => 'normal', 'level' => 72, 'base_hp' => 275, 'base_atq' => 118, 'base_def' => 22, 'base_vit' => 30, 'base_int' => 15, 'base_cha' => 10, 'element' => 'physique', 'xp_reward' => 725, 'gold_min' => 80, 'gold_max' => 160, 'loot_bonus' => 20, 'behavior_data' => json_encode(['priority' => 'random', 'burst_and_vanish' => true, 'gold_steal_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Mage de Rue', 'slug' => 'mage_rue', 'monster_type' => 'normal', 'level' => 73, 'base_hp' => 235, 'base_atq' => 100, 'base_def' => 18, 'base_vit' => 22, 'base_int' => 95, 'base_cha' => 0, 'element' => 'foudre', 'xp_reward' => 740, 'gold_min' => 60, 'gold_max' => 120, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'cast_and_run' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Golem de la Guilde', 'slug' => 'golem_guilde', 'monster_type' => 'normal', 'level' => 75, 'base_hp' => 600, 'base_atq' => 80, 'base_def' => 85, 'base_vit' => 5, 'base_int' => 10, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 760, 'gold_min' => 50, 'gold_max' => 100, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'random', 'reflect_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Rat d\'Égout Mutant', 'slug' => 'rat_egout_mutant', 'monster_type' => 'normal', 'level' => 76, 'base_hp' => 310, 'base_atq' => 92, 'base_def' => 28, 'base_vit' => 24, 'base_int' => 15, 'base_cha' => 0, 'element' => 'poison', 'xp_reward' => 775, 'gold_min' => 50, 'gold_max' => 100, 'loot_bonus' => 10, 'behavior_data' => json_encode(['priority' => 'random', 'summon_rats_4' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Marchand Rival', 'slug' => 'marchand_rival', 'monster_type' => 'normal', 'level' => 77, 'base_hp' => 340, 'base_atq' => 68, 'base_def' => 38, 'base_vit' => 18, 'base_int' => 40, 'base_cha' => 30, 'element' => 'physique', 'xp_reward' => 790, 'gold_min' => 100, 'gold_max' => 200, 'loot_bonus' => 25, 'behavior_data' => json_encode(['priority' => 'random', 'debuff_economy_chance' => 30]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Assassin de la Guilde', 'slug' => 'assassin_guilde', 'monster_type' => 'normal', 'level' => 79, 'base_hp' => 250, 'base_atq' => 130, 'base_def' => 12, 'base_vit' => 32, 'base_int' => 25, 'base_cha' => 0, 'element' => 'ombre', 'xp_reward' => 810, 'gold_min' => 70, 'gold_max' => 140, 'loot_bonus' => 15, 'behavior_data' => json_encode(['priority' => 'lowest_hp', 'ambush_on_enter' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Statue Vivante', 'slug' => 'statue_vivante', 'monster_type' => 'normal', 'level' => 80, 'base_hp' => 750, 'base_atq' => 55, 'base_def' => 100, 'base_vit' => 2, 'base_int' => 5, 'base_cha' => 0, 'element' => 'physique', 'xp_reward' => 820, 'gold_min' => 45, 'gold_max' => 90, 'loot_bonus' => 20, 'behavior_data' => json_encode(['priority' => 'random', 'passive_unless_hit' => true, 'reflect_all' => true]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Le Maître de la Guilde des Zéros', 'slug' => 'maitre_guilde_zeros', 'monster_type' => 'mini_boss', 'level' => 78, 'base_hp' => 5000, 'base_atq' => 120, 'base_def' => 65, 'base_vit' => 20, 'base_int' => 70, 'base_cha' => 35, 'element' => 'physique', 'xp_reward' => 6500, 'gold_min' => 900, 'gold_max' => 1700, 'loot_bonus' => 60, 'behavior_data' => json_encode(['priority' => 'highest_atq', 'summon_incompetent_guards' => true, 'friendly_fire_chance' => 20]), 'phase2_data' => null, 'is_active' => 1],
            ['zone_id' => $capitId, 'name' => 'Le Maire de la Capitale', 'slug' => 'maire_capitale', 'monster_type' => 'boss', 'level' => 85, 'base_hp' => 15000, 'base_atq' => 135, 'base_def' => 75, 'base_vit' => 18, 'base_int' => 110, 'base_cha' => 50, 'element' => 'glace', 'xp_reward' => 20000, 'gold_min' => 2000, 'gold_max' => 4000, 'loot_bonus' => 100, 'behavior_data' => json_encode(['priority' => 'random', 'three_phases' => true, 'gold_drain_per_turn' => 50]), 'phase2_data' => json_encode(['hp_threshold' => 33, 'stat_multiplier' => 150, 'narrator_text' => 'Le Maire a retourné son bureau. La politique, c\'est fini.']), 'is_active' => 1],
        ];

        foreach ($monsters as $monster) {
            DB::table('monsters')->updateOrInsert(['slug' => $monster['slug']], $monster);
        }

        $this->seedMonsterSkills();
    }

    private function seedMonsterSkills(): void
    {
        // Only insert if not already present
        $skillDefs = [
            // Zone 1
            ['gobelin_chapardeur', 'Vol Éclair', 'Vole de l\'or', 'special', 0, 3, 30, ['gold_steal_percent' => 10]],
            ['abeille_geante', 'Dard Vénéneux', 'Poison 3 tours', 'debuff', 80, 2, 40, ['poison_per_turn' => 3, 'duration' => 3]],
            ['fermier_possede', 'Fourche Démoniaque', 'Réduit la DEF', 'attaque', 150, 3, 40, ['def_reduce_percent' => 20, 'duration' => 2]],
            ['taureau_pre_maudit', 'Charge Bestiale', 'Frappe tout', 'attaque', 120, 3, 35, ['targets' => 'all_heroes']],
            // Zone 2
            ['fee_malveillante', 'Malédiction Fée', '-20% stats 2 tours', 'debuff', 60, 3, 35, ['all_stats_reduce' => 20, 'duration' => 2]],
            ['elara_elfe_vexee_mini', 'Pluie de Flèches', 'Touche toute l\'équipe', 'attaque', 90, 4, 30, ['targets' => 'all_heroes']],
            ['esprit_foret_tres_enerve', 'Tempête de Feuilles', 'Toute l\'équipe', 'attaque', 110, 5, 25, ['targets' => 'all_heroes']],
            // Zone 3
            ['troll_tunnels', 'Régénération Trollique', 'Récupère des PV', 'special', 0, 1, 100, ['heal_per_turn' => 5]],
            ['dragon_mines_retraite', 'Souffle de Feu (retraité)', 'Dégâts de feu à tous', 'attaque', 130, 5, 30, ['targets' => 'all_heroes', 'element' => 'feu']],
            // Zone 4
            ['hydre_formulaires', 'Attaque Multiple', '3 cibles aléatoires', 'attaque', 80, 3, 40, ['targets' => 'random_3']],
            ['kraken_comptable', 'Audit Fiscal', 'Vole de l\'or + debuff', 'special', 50, 5, 35, ['gold_steal_percent' => 20, 'stat_reduce' => 15, 'duration' => 3]],
            ['kraken_comptable', 'Tentacules en Masse', 'Frappe toute l\'équipe', 'attaque', 100, 4, 35, ['targets' => 'all_heroes']],
        ];

        foreach ($skillDefs as [$slug, $name, $desc, $type, $dmgPct, $cd, $chance, $effects]) {
            $monsterId = DB::table('monsters')->where('slug', $slug)->value('id');
            if ($monsterId) {
                $exists = DB::table('monster_skills')
                    ->where('monster_id', $monsterId)
                    ->where('name', $name)
                    ->exists();
                if (!$exists) {
                    DB::table('monster_skills')->insert([
                        'monster_id'     => $monsterId,
                        'name'           => $name,
                        'description'    => $desc,
                        'skill_type'     => $type,
                        'damage_percent' => $dmgPct,
                        'cooldown_turns' => $cd,
                        'use_chance'     => $chance,
                        'effect_data'    => json_encode($effects),
                    ]);
                }
            }
        }
    }
}
