<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Recettes découvrables spécifiques à chaque zone (3 par zone).
 * Sources : ECONOMY.md §8.2
 */
class RecipeZoneSeeder extends Seeder
{
    public function run(): void
    {
        $zones = DB::table('zones')->pluck('id', 'slug');

        $prairie   = $zones['prairie']                  ?? null;
        $foret     = $zones['foret_elfes']              ?? null;
        $mines     = $zones['mines_nain']               ?? null;
        $marais    = $zones['marais_bureaucratie']       ?? null;
        $tour      = $zones['tour_mage_distrait']        ?? null;
        $cimetiere = $zones['cimetiere_syndique']        ?? null;
        $volcan    = $zones['volcan_dragon_retraite']    ?? null;
        $capitale  = $zones['capitale_incompetents']     ?? null;

        $recipes = [

            // ── Zone 1 — Prairie des Débutants ──────────────────────────────
            [
                'name'               => 'Amulette du Débutant',
                'description'        => '+5% XP en permanence. Idéal pour progresser plus vite et compenser l\'incompétence.',
                'ingredients'        => json_encode([['slug' => 'ferraille', 'qty' => 5], ['slug' => 'cuir', 'qty' => 3]]),
                'gold_cost'          => 200,
                'result_type'        => 'item',
                'result_slot'        => 'accessoire',
                'result_rarity'      => 'peu_commun',
                'result_level'       => 2,
                'result_stats'       => json_encode(['cha' => 5, 'hp' => 10]),
                'result_name'        => 'Amulette du Débutant',
                'result_description' => 'Bonus XP. Pour ceux qui savent qu\'ils partent de loin.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $prairie,
            ],
            [
                'name'               => 'Cape du Berger',
                'description'        => 'Armure légère tissée de laine enchantée. Résiste au froid et aux commentaires des passants.',
                'ingredients'        => json_encode([['slug' => 'laine_enchantee', 'qty' => 3], ['slug' => 'cuir', 'qty' => 5]]),
                'gold_cost'          => 400,
                'result_type'        => 'item',
                'result_slot'        => 'armure',
                'result_rarity'      => 'peu_commun',
                'result_level'       => 3,
                'result_stats'       => json_encode(['def' => 12, 'hp' => 20]),
                'result_name'        => 'Cape du Berger',
                'result_description' => 'Douce, chaleureuse, légèrement encombrante. Exactement comme son ancien propriétaire.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $prairie,
            ],
            [
                'name'               => 'Gourdin de Corne',
                'description'        => 'Arme contondante taillée dans une corne de bête. Chance d\'étourdir sur coup critique.',
                'ingredients'        => json_encode([['slug' => 'corne_bete', 'qty' => 4], ['slug' => 'ferraille', 'qty' => 3]]),
                'gold_cost'          => 300,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'peu_commun',
                'result_level'       => 2,
                'result_stats'       => json_encode(['atq' => 12, 'vit' => 4]),
                'result_name'        => 'Gourdin de Corne',
                'result_description' => 'La finesse, c\'est surfait. Ce truc fait mal.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $prairie,
            ],

            // ── Zone 2 — Forêt des Elfes Vexés ──────────────────────────────
            [
                'name'               => 'Arc des Elfes Vexés',
                'description'        => 'L\'arc préféré d\'Elara — mais elle l\'a donné parce qu\'elle était de mauvaise humeur.',
                'ingredients'        => json_encode([['slug' => 'bois_elfique', 'qty' => 5], ['slug' => 'fil_araignee', 'qty' => 3]]),
                'gold_cost'          => 800,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'rare',
                'result_level'       => 8,
                'result_stats'       => json_encode(['atq' => 22, 'vit' => 12, 'int' => 8]),
                'result_name'        => 'Arc des Elfes Vexés',
                'result_description' => 'Un arc elfique. Tire avec précision ET condescendance.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $foret,
            ],
            [
                'name'               => 'Armure de Soie d\'Araignée',
                'description'        => 'Tissée de fil d\'araignée, légère comme une insulte elfique et aussi résistante.',
                'ingredients'        => json_encode([['slug' => 'fil_araignee', 'qty' => 5], ['slug' => 'cuir', 'qty' => 3]]),
                'gold_cost'          => 1000,
                'result_type'        => 'item',
                'result_slot'        => 'armure',
                'result_rarity'      => 'rare',
                'result_level'       => 10,
                'result_stats'       => json_encode(['def' => 25, 'vit' => 15, 'hp' => 20]),
                'result_name'        => 'Armure de Soie d\'Araignée',
                'result_description' => 'Souple, résistante, légèrement collante. Comme toute bonne armure.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $foret,
            ],
            [
                'name'               => 'Diadème de Fée',
                'description'        => 'Casque enchanté orné de plumes de fée. Améliore l\'intelligence et le charme, pas la lucidité.',
                'ingredients'        => json_encode([['slug' => 'plume_fee', 'qty' => 3], ['slug' => 'gemme_brute', 'qty' => 2]]),
                'gold_cost'          => 1200,
                'result_type'        => 'item',
                'result_slot'        => 'casque',
                'result_rarity'      => 'rare',
                'result_level'       => 8,
                'result_stats'       => json_encode(['int' => 20, 'cha' => 15]),
                'result_name'        => 'Diadème de Fée',
                'result_description' => 'Brillant, léger, inutile au combat. Parfait pour les réceptions.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $foret,
            ],

            // ── Zone 3 — Mines du Nain Ivre ──────────────────────────────────
            [
                'name'               => 'Hache du Mineur',
                'description'        => 'Forgée dans les profondeurs avec du minerai brut et une pointe de lave. Thorin approuve.',
                'ingredients'        => json_encode([['slug' => 'minerai_brut', 'qty' => 5], ['slug' => 'ferraille', 'qty' => 3], ['slug' => 'eclat_lave', 'qty' => 1]]),
                'gold_cost'          => 1500,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'rare',
                'result_level'       => 12,
                'result_stats'       => json_encode(['atq' => 35, 'vit' => 8]),
                'result_name'        => 'Hache du Mineur',
                'result_description' => 'Faite pour creuser. Marche aussi pour trancher. Polyvalent.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $mines,
            ],
            [
                'name'               => 'Casque du Nain Blindé',
                'description'        => 'DEF solide + résistance aux étourdissements. Thorin l\'a forgé en étant ivre. C\'est dit.',
                'ingredients'        => json_encode([['slug' => 'minerai_brut', 'qty' => 8], ['slug' => 'pierre_lumineuse', 'qty' => 2]]),
                'gold_cost'          => 1800,
                'result_type'        => 'item',
                'result_slot'        => 'casque',
                'result_rarity'      => 'rare',
                'result_level'       => 14,
                'result_stats'       => json_encode(['def' => 30, 'hp' => 40]),
                'result_name'        => 'Casque du Nain Blindé',
                'result_description' => 'Forgé ivre. Résiste quand même. Impressionnant.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $mines,
            ],
            [
                'name'               => 'Lanterne de Mine',
                'description'        => 'Accessoire lumineux qui améliore les chances de loot en souterrain. Pratique.',
                'ingredients'        => json_encode([['slug' => 'pierre_lumineuse', 'qty' => 3], ['slug' => 'ferraille', 'qty' => 5]]),
                'gold_cost'          => 1000,
                'result_type'        => 'item',
                'result_slot'        => 'accessoire',
                'result_rarity'      => 'rare',
                'result_level'       => 10,
                'result_stats'       => json_encode(['vit' => 10, 'cha' => 15]),
                'result_name'        => 'Lanterne de Mine',
                'result_description' => '+15% loot en souterrain. Dans le noir, tout le monde vous voit briller.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $mines,
            ],

            // ── Zone 4 — Marais de la Bureaucratie ───────────────────────────
            [
                'name'               => 'Formulaire en Triple Exemplaire',
                'description'        => 'Paralyse un ennemi pendant 2 tours avec de la paperasserie. Légal partout.',
                'ingredients'        => json_encode([['slug' => 'papier_officiel', 'qty' => 8], ['slug' => 'encre_toxique', 'qty' => 3]]),
                'gold_cost'          => 2500,
                'result_type'        => 'item',
                'result_slot'        => 'accessoire',
                'result_rarity'      => 'epique',
                'result_level'       => 22,
                'result_stats'       => json_encode(['cha' => 25, 'int' => 20]),
                'result_name'        => 'Formulaire en Triple Exemplaire',
                'result_description' => 'Paperasserie offensive. Paralyse moralement les ennemis.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $marais,
            ],
            [
                'name'               => 'Bottes du Marais',
                'description'        => 'Bottes conçues pour le terrain boueux. Immunité au Ralenti et VIT bonifiée.',
                'ingredients'        => json_encode([['slug' => 'vase_magique', 'qty' => 5], ['slug' => 'cuir', 'qty' => 3]]),
                'gold_cost'          => 2000,
                'result_type'        => 'item',
                'result_slot'        => 'bottes',
                'result_rarity'      => 'rare',
                'result_level'       => 18,
                'result_stats'       => json_encode(['vit' => 30, 'def' => 15]),
                'result_name'        => 'Bottes du Marais',
                'result_description' => 'Imperméables, rapides, et ça fait "floc" à chaque pas. Classe.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $marais,
            ],
            [
                'name'               => 'Stylo-Dague',
                'description'        => 'Une arme-outil hybride : inflige des dégâts Poison et fait des copies en trois exemplaires.',
                'ingredients'        => json_encode([['slug' => 'encre_toxique', 'qty' => 5], ['slug' => 'tampon_use', 'qty' => 3], ['slug' => 'cristal_brut', 'qty' => 1]]),
                'gold_cost'          => 3000,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'epique',
                'result_level'       => 20,
                'result_stats'       => json_encode(['atq' => 45, 'int' => 25]),
                'result_name'        => 'Stylo-Dague',
                'result_description' => 'La bureaucratie comme arme létale. Enfin.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $marais,
            ],

            // ── Zone 5 — Tour du Mage Distrait ───────────────────────────────
            [
                'name'               => 'Orbe Instable',
                'description'        => 'Orbe magique à variance élargie. Peut faire très mal. Ou presque rien. Mystère.',
                'ingredients'        => json_encode([['slug' => 'poussiere_arcanique', 'qty' => 5], ['slug' => 'eclat_foudre', 'qty' => 3], ['slug' => 'cristal_brut', 'qty' => 1]]),
                'gold_cost'          => 4000,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'epique',
                'result_level'       => 25,
                'result_stats'       => json_encode(['int' => 55, 'atq' => 20]),
                'result_name'        => 'Orbe Instable',
                'result_description' => 'Instable. C\'est dans le nom. Vous étiez prévenus.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $tour,
            ],
            [
                'name'               => 'Robe du Temps',
                'description'        => 'Armure imprégnée de magie temporelle. 5% de chance de sauter le tour d\'un ennemi.',
                'ingredients'        => json_encode([['slug' => 'rouage_magique', 'qty' => 5], ['slug' => 'page_enchantee', 'qty' => 3]]),
                'gold_cost'          => 3500,
                'result_type'        => 'item',
                'result_slot'        => 'armure',
                'result_rarity'      => 'epique',
                'result_level'       => 25,
                'result_stats'       => json_encode(['def' => 40, 'int' => 30]),
                'result_name'        => 'Robe du Temps',
                'result_description' => 'Porter cette robe, c\'est vivre légèrement dans le futur. Ou le passé. Difficile à dire.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $tour,
            ],
            [
                'name'               => 'Montre de Poche Folle',
                'description'        => 'Accessoire mécanique qui calcule l\'initiative deux fois et garde le meilleur résultat.',
                'ingredients'        => json_encode([['slug' => 'rouage_magique', 'qty' => 3], ['slug' => 'eclat_foudre', 'qty' => 2], ['slug' => 'gemme_brute', 'qty' => 1]]),
                'gold_cost'          => 3000,
                'result_type'        => 'item',
                'result_slot'        => 'accessoire',
                'result_rarity'      => 'rare',
                'result_level'       => 22,
                'result_stats'       => json_encode(['vit' => 45, 'int' => 15]),
                'result_name'        => 'Montre de Poche Folle',
                'result_description' => 'Elle avance. Elle recule. Elle décide quand vous agissez. Fascinant.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $tour,
            ],

            // ── Zone 6 — Cimetière Syndiqué ──────────────────────────────────
            [
                'name'               => 'Faux du Fossoyeur',
                'description'        => 'Arme épique aux dégâts Sacrés. +25% de dégâts contre les morts-vivants.',
                'ingredients'        => json_encode([['slug' => 'os_poli', 'qty' => 8], ['slug' => 'essence_ombre', 'qty' => 3], ['slug' => 'cristal_brut', 'qty' => 1]]),
                'gold_cost'          => 5000,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'epique',
                'result_level'       => 28,
                'result_stats'       => json_encode(['atq' => 70, 'int' => 25]),
                'result_name'        => 'Faux du Fossoyeur',
                'result_description' => 'Ironie maximale : tuer des morts avec l\'outil du fossoyeur.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $cimetiere,
            ],
            [
                'name'               => 'Cape d\'Ectoplasme',
                'description'        => 'Armure spectrale offrant 10% d\'esquive et résistance aux dégâts d\'Ombre.',
                'ingredients'        => json_encode([['slug' => 'ectoplasme', 'qty' => 5], ['slug' => 'bandage_maudit', 'qty' => 3]]),
                'gold_cost'          => 4000,
                'result_type'        => 'item',
                'result_slot'        => 'armure',
                'result_rarity'      => 'rare',
                'result_level'       => 25,
                'result_stats'       => json_encode(['def' => 45, 'vit' => 15]),
                'result_name'        => 'Cape d\'Ectoplasme',
                'result_description' => 'Semi-matérielle. Les coups passent parfois à travers. C\'est un avantage, pas un défaut.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $cimetiere,
            ],
            [
                'name'               => 'Crâne Ricanant',
                'description'        => 'Accessoire macabre. 8% de chance d\'appliquer Terrifié à chaque attaque.',
                'ingredients'        => json_encode([['slug' => 'os_poli', 'qty' => 5], ['slug' => 'ectoplasme', 'qty' => 3], ['slug' => 'essence_majeure', 'qty' => 1]]),
                'gold_cost'          => 6000,
                'result_type'        => 'item',
                'result_slot'        => 'accessoire',
                'result_rarity'      => 'epique',
                'result_level'       => 28,
                'result_stats'       => json_encode(['int' => 50, 'cha' => 40]),
                'result_name'        => 'Crâne Ricanant',
                'result_description' => 'Il rigole tout le temps. C\'est dérangeant. C\'est le but.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $cimetiere,
            ],

            // ── Zone 7 — Volcan du Dragon Retraité ───────────────────────────
            [
                'name'               => 'Lame de Magma',
                'description'        => 'Épée forgée dans l\'obsidienne volcanique. Dégâts de Feu, 15% de chance d\'Enflammer.',
                'ingredients'        => json_encode([['slug' => 'obsidienne', 'qty' => 8], ['slug' => 'cendre_volcanique', 'qty' => 3], ['slug' => 'cristal_brut', 'qty' => 2]]),
                'gold_cost'          => 8000,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'epique',
                'result_level'       => 32,
                'result_stats'       => json_encode(['atq' => 100, 'vit' => 15]),
                'result_name'        => 'Lame de Magma',
                'result_description' => 'Chaude à tenir. Encore plus chaude pour celui qui la reçoit.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $volcan,
            ],
            [
                'name'               => 'Plastron Draconique',
                'description'        => 'Armure forgée d\'écailles de dragon. Résistance Feu +30%. Le dragon est mécontent.',
                'ingredients'        => json_encode([['slug' => 'ecaille_dragon', 'qty' => 3], ['slug' => 'obsidienne', 'qty' => 5], ['slug' => 'essence_majeure', 'qty' => 1]]),
                'gold_cost'          => 12000,
                'result_type'        => 'item',
                'result_slot'        => 'armure',
                'result_rarity'      => 'epique',
                'result_level'       => 35,
                'result_stats'       => json_encode(['def' => 120, 'hp' => 80]),
                'result_name'        => 'Plastron Draconique',
                'result_description' => 'Fabriqué avec les restes d\'un dragon retraité. Il n\'apprécierait pas.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $volcan,
            ],
            [
                'name'               => 'Anneau du Phénix',
                'description'        => 'Accessoire légendaire. 1×/combat, si K.O., revient à 30% PV.',
                'ingredients'        => json_encode([['slug' => 'plume_phenix', 'qty' => 3], ['slug' => 'cendre_volcanique', 'qty' => 2], ['slug' => 'fragment_stellaire', 'qty' => 1]]),
                'gold_cost'          => 15000,
                'result_type'        => 'item',
                'result_slot'        => 'accessoire',
                'result_rarity'      => 'legendaire',
                'result_level'       => 35,
                'result_stats'       => json_encode(['hp' => 150, 'atq' => 60]),
                'result_name'        => 'Anneau du Phénix',
                'result_description' => 'Mourir avec style, et revenir aussitôt. Classe absolue.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $volcan,
            ],

            // ── Zone 8 — Capitale des Incompétents ───────────────────────────
            [
                'name'               => 'Épée du Champion',
                'description'        => 'L\'arme des élus de la Capitale. ATQ très élevée, +10% toutes stats en zone Capitale.',
                'ingredients'        => json_encode([['slug' => 'acier_ville', 'qty' => 8], ['slug' => 'insigne_guilde', 'qty' => 3], ['slug' => 'essence_majeure', 'qty' => 2]]),
                'gold_cost'          => 10000,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'epique',
                'result_level'       => 38,
                'result_stats'       => json_encode(['atq' => 140, 'vit' => 20]),
                'result_name'        => 'Épée du Champion',
                'result_description' => 'Le titre "champion" est très relatif dans cette ville.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $capitale,
            ],
            [
                'name'               => 'Armure de Prestige',
                'description'        => 'Armure officielle de la guilde. DEF + CHA, -10% prix dans les boutiques.',
                'ingredients'        => json_encode([['slug' => 'acier_ville', 'qty' => 5], ['slug' => 'insigne_guilde', 'qty' => 3], ['slug' => 'cuir', 'qty' => 5]]),
                'gold_cost'          => 8000,
                'result_type'        => 'item',
                'result_slot'        => 'armure',
                'result_rarity'      => 'epique',
                'result_level'       => 38,
                'result_stats'       => json_encode(['def' => 120, 'cha' => 60]),
                'result_name'        => 'Armure de Prestige',
                'result_description' => 'Porter ça, c\'est avoir l\'air important. Le résultat est parfois le même que l\'être.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $capitale,
            ],
            [
                'name'               => 'Dague de l\'Ombre',
                'description'        => 'Arme furtive à dégâts d\'Ombre. Le premier coup est toujours un critique.',
                'ingredients'        => json_encode([['slug' => 'poudre_ombre', 'qty' => 5], ['slug' => 'acier_ville', 'qty' => 3], ['slug' => 'essence_majeure', 'qty' => 1]]),
                'gold_cost'          => 9000,
                'result_type'        => 'item',
                'result_slot'        => 'arme',
                'result_rarity'      => 'epique',
                'result_level'       => 36,
                'result_stats'       => json_encode(['atq' => 110, 'vit' => 50]),
                'result_name'        => 'Dague de l\'Ombre',
                'result_description' => 'N\'existe pas. Vous ne l\'avez jamais vue. Personne ne l\'a vue.',
                'is_discoverable'    => true,
                'unlock_zone_id'     => $capitale,
            ],
        ];

        foreach ($recipes as $recipe) {
            $recipe['created_at'] = now();
            $recipe['updated_at'] = now();
            DB::table('recipes')->insertOrIgnore($recipe);
        }
    }
}
