<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TraitSeeder extends Seeder
{
    public function run(): void
    {
        $traits = [
            [
                'slug' => 'couard',
                'name' => 'Couard',
                'description' => '15% de chance de fuir un combat',
                'flavor_text' => '"La fuite, c\'est une stratégie."',
                'trigger_moment' => 'turn_start',
                'base_chance' => 15,
                'chance_level_26' => 18,
                'chance_level_51' => 20,
                'chance_level_76' => 15,
                'effect_data' => json_encode(['action' => 'flee', 'skip_turn' => true]),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'narcoleptique',
                'name' => 'Narcoleptique',
                'description' => '10% de chance de s\'endormir pendant un combat (skip un tour)',
                'flavor_text' => '"Zzz... Quoi ? On est attaqués ?"',
                'trigger_moment' => 'turn_start',
                'base_chance' => 10,
                'chance_level_26' => 12,
                'chance_level_51' => 8,
                'chance_level_76' => 5,
                'effect_data' => json_encode(['action' => 'sleep', 'skip_turn' => true, 'duration' => 2, 'wake_chance' => 50]),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'kleptomane',
                'name' => 'Kleptomane',
                'description' => 'Vole parfois le loot des alliés',
                'flavor_text' => '"C\'était dans ma poche depuis le début."',
                'trigger_moment' => 'after_combat',
                'base_chance' => 20,
                'chance_level_26' => 25,
                'chance_level_51' => 30,
                'chance_level_76' => 35,
                'effect_data' => json_encode(['action' => 'steal_loot', 'skip_turn' => false, 'synergy_class' => 'voleur']),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'pyromane',
                'name' => 'Pyromane',
                'description' => '20% de chance de mettre le feu au décor (dégâts de zone)',
                'flavor_text' => '"Le feu, ça résout tout."',
                'trigger_moment' => 'after_attack',
                'base_chance' => 20,
                'chance_level_26' => 22,
                'chance_level_51' => 25,
                'chance_level_76' => 28,
                'effect_data' => json_encode(['action' => 'aoe_fire', 'skip_turn' => false, 'damage_percent' => 8, 'friendly_fire' => true]),
                'scaling_data' => json_encode(['damage_percent_per_10_levels' => 1]),
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'allergique',
                'name' => 'Allergique à la Magie',
                'description' => 'Malus en zone magique, éternue et révèle la position',
                'flavor_text' => '"ATCHOUM — ah, le boss nous a vus."',
                'trigger_moment' => 'turn_start',
                'base_chance' => 25,
                'chance_level_26' => 20,
                'chance_level_51' => 15,
                'chance_level_76' => 10,
                'effect_data' => json_encode(['action' => 'sneeze', 'skip_turn' => true, 'malus_percent' => 20, 'only_in_magic_zone' => true]),
                'scaling_data' => null,
                'out_of_combat_effect' => 'Malus de -20% à toutes les stats en zones magiques',
            ],
            [
                'slug' => 'philosophe',
                'name' => 'Philosophe',
                'description' => 'S\'arrête en plein combat pour réfléchir (skip un tour)',
                'flavor_text' => '"Mais au fond, pourquoi combattre ?"',
                'trigger_moment' => 'turn_start',
                'base_chance' => 12,
                'chance_level_26' => 10,
                'chance_level_51' => 8,
                'chance_level_76' => 5,
                'effect_data' => json_encode(['action' => 'ponder', 'skip_turn' => true, 'int_buff_percent' => 15]),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'gourmand',
                'name' => 'Gourmand',
                'description' => 'Consomme les potions de soin automatiquement même à PV max',
                'flavor_text' => '"C\'était pas du jus de pomme ?"',
                'trigger_moment' => 'turn_start',
                'base_chance' => 25,
                'chance_level_26' => 30,
                'chance_level_51' => 35,
                'chance_level_76' => 40,
                'effect_data' => json_encode(['action' => 'consume_potion', 'skip_turn' => false, 'even_at_full_hp' => true]),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'superstitieux',
                'name' => 'Superstitieux',
                'description' => 'Refuse d\'entrer dans certains donjons selon le jour',
                'flavor_text' => '"Pas un mardi ! Jamais un mardi !"',
                'trigger_moment' => 'dungeon_entry',
                'base_chance' => 15,
                'chance_level_26' => 12,
                'chance_level_51' => 10,
                'chance_level_76' => 5,
                'effect_data' => json_encode(['action' => 'refuse_dungeon', 'skip_turn' => true]),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
            [
                'slug' => 'mythomane',
                'name' => 'Mythomane',
                'description' => 'Ses stats affichées sont fausses (±20% aléatoire)',
                'flavor_text' => '"J\'ai déjà tué un dragon. Enfin, un gros lézard."',
                'trigger_moment' => 'permanent',
                'base_chance' => 100,
                'chance_level_26' => 100,
                'chance_level_51' => 100,
                'chance_level_76' => 100,
                'effect_data' => json_encode(['action' => 'display_variance', 'skip_turn' => false, 'variance_percent' => 20]),
                'scaling_data' => null,
                'out_of_combat_effect' => 'Stats affichées ±20% de la vraie valeur',
            ],
            [
                'slug' => 'pacifiste',
                'name' => 'Pacifiste',
                'description' => 'Refuse d\'attaquer certains ennemis "trop mignons"',
                'flavor_text' => '"Non mais regarde sa petite tête !"',
                'trigger_moment' => 'on_target_low_hp',
                'base_chance' => 15,
                'chance_level_26' => 12,
                'chance_level_51' => 10,
                'chance_level_76' => 8,
                'effect_data' => json_encode(['action' => 'refuse_attack', 'skip_turn' => true, 'hp_threshold_percent' => 30]),
                'scaling_data' => null,
                'out_of_combat_effect' => null,
            ],
        ];

        foreach ($traits as $trait) {
            DB::table('traits')->updateOrInsert(['slug' => $trait['slug']], $trait);
        }
    }
}
